### ISSUE TITLE
Can't start editing

### ISSUE THREAD

**Issue by mathetes** [tinacms/tina-starter-alpaca#101]
In terminal I have such warning info

`npm run dev

> tina-alpaca@0.1.0 dev /home/mathetes/01_DEV/03_React/CMS/alpaca
> next

Loaded env from /home/mathetes/01_DEV/03_React/CMS/alpaca/.env.development
Loaded env from /home/mathetes/01_DEV/03_React/CMS/alpaca/.env
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /blog
wait  - compiling...
event - build page: /api/proxy-github
warn  - ./node_modules/markdown-toc/lib/utils.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
info  - ready on http://localhost:3000
`

**Comment by DirtyF** [comment]
This is working fine on my end. 🤔 

![CleanShot 2021-02-26 at 14 17 13@2x](https://user-images.githubusercontent.com/103008/109305113-8daa0480-783d-11eb-9a93-0950b3763a28.png)

- Did you fork the repo?
- Did you setup a GitHub OAuth app on localhost:3000?

**Comment by mathetes** [comment]
Yes I clone it to my local folder & after I push it on my personal [repo](https://github.com/mathetes/unity-tinacms)

**Comment by DirtyF** [comment]
And did you report the variables from your local GitHub IAuth app in your .env file?
Also could you share your environment (Node version, OS)?

**Comment by DirtyF** [comment]
Closing, for now, feel free to reopen if you have more info to share.

Maybe try with yarn instead of npm?
