### ISSUE TITLE
Media/Image support

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-starter-alpaca#54]
Alpaca should allow for image embed inside the editor.

**Comment by DirtyF** [comment]
@scottgallant For now, you should still be able to drag and drop an image in th editori

**Comment by DirtyF** [comment]
@logan-anderson can we upgrade the starter to the latest Tina packages, react-editor should support this

**Comment by chrisdmacrae** [comment]
@logan-anderson @DirtyF as a recommendation, this could be semi-automated on our starters w/ [renovatebot](https://github.com/marketplace/renovate), so at least PRs automatically open when downstream deps get upgraded, and we'd get notifications.

**Comment by DirtyF** [comment]
@chrisdmacrae Good idea, I don't have proper rights to install the bot. GitHub has dependabot now.

**Comment by logan-anderson** [comment]
@DirtyF @chrisdmacrae One thing to note is that sometimes tinaCMS packages have breaking changes. currently trying to upgrade now and having some trouble. if we do add something like this make sure that is thoroughly tested before merged.

**Comment by DirtyF** [comment]
@logan-anderson you can count on me for testing. It will help us see if we need to provide upgrade instructions for tinacms-packages.

**Comment by logan-anderson** [comment]
@DirtyF this will be fixed with #58
