### ISSUE TITLE
Exit Tina button

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tina-starter-alpaca#55]
We should remove the Preview and Edit buttons on the page and make use of the Tina Exit button: 

<img width="490" alt="Screen Shot 2020-06-25 at 1 05 03 PM" src="https://user-images.githubusercontent.com/776019/85755642-821da100-b6e4-11ea-83b9-e88babac7f55.png">

The exit button can be seen in the inline-blocks demo here:

<img width="647" alt="Screen Shot 2020-06-25 at 1 03 48 PM" src="https://user-images.githubusercontent.com/776019/85755600-792ccf80-b6e4-11ea-83fb-a7fd222c94eb.png">

**Comment by DirtyF** [comment]
Same here @logan-anderson upgrading to latest Tina packages is needed.

**Comment by logan-anderson** [comment]
@DirtyF this will be fixed with #58
