### ISSUE TITLE
Edit This Site With TinaCMS button hidden below fold

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-starter-alpaca#60]
The button to start editing content is in the footer. The footer is displayed below the page fold. On pages with little content, it's not obvious to a user that they need to scroll down to find the button.

![alpaca-spacing](https://user-images.githubusercontent.com/618212/86624078-19aea980-bf99-11ea-8c2a-5882d053bafe.png)

Ways to possibly make it more obvious:

- adjust the min-height on the page content container so that the footer isn't pushed below the fold
- move it to the header (probably not visually desirable in as many use cases)

**Comment by logan-anderson** [comment]
I agree and this should be an easy fix.
