### ISSUE TITLE
"Exit Tina" isn't reflected after page reload

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-starter-alpaca#62]
Maybe I don't understand the purpose of the "Exit Tina" button in the header, but it seems to not persist after refreshing the page.

Steps to reproduce:

- Go to https://tina-starter-alpaca.now.sh/docs/getting-started
- Click "Edit This Site With TinaCMS"
- Click "Exit Tina"
- Reload page, Editing mode is re-enabled
![exit-tina](https://user-images.githubusercontent.com/618212/86630757-a0688400-bfa3-11ea-9c89-3cb335ee1583.png)

**Comment by logan-anderson** [comment]
@ncphillips is this a bug with Tina?

**Comment by chrisdmacrae** [comment]
@logan-anderson the active editing logic is handled in the downstream site, not Tina. So I guess we should be registering the "exit" logic to the TinaProvider and running it.

**Comment by ncphillips** [comment]
@chrisdmacrae it actually should be bound. The Exit Tina button dispatches a `cms:disabled` event which the `TinaGithubProvider` should be watching for. When that event fires it should call `onLogout`

@logan-anderson could you try this with the pre-release `@next` version of the tina packages?

**Comment by logan-anderson** [comment]
@ncphillips  that fixes it
