### ISSUE TITLE
WYSIWYG toolbar is not sticky by default

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-starter-alpaca#70]
**Issue**

```gherkin
Given I edit a long text
When I scroll down the page
Then I can not see the WYSIWYG toolbar
```

<img width="1436" alt="Capture d’écran 2020-07-16 à 16 31 35" src="https://user-images.githubusercontent.com/103008/87683922-ebdc1880-c781-11ea-94e1-472bfedd4b36.png">

**Expected**
Toolbar is always visible when I edit text.

There's already a `sticky` option, but the documentation does not say what the default value is:
https://tinacms.org/docs/inline-editing/inline-wysiwyg#options

**Comment by logan-anderson** [comment]
yeah, we need to add an offset. It should be an easy fix once we do the next release.
